name: PR Notification

on:
  pull_request:
    types:
      - opened
      - edited
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      uses: Ilshidur/action-discord@v1
      with:
        webhook_url: 'https://discord.com/api/webhooks/1350588875646435388/Rnoj1zDeRb8R6kZqw788Pm5CoMQxv-J-Do83UIcEYAaulsW0Tl_Uz7PHAuzxqJDWhu1s'
        username: 'Sunnygirl169'
        avatar_url: 'https://cdn.discordapp.com/avatars/1350588875646435388/ee34f59351e2232cc374ef4a5d0c6b19.png'
        content: |
          **New Pull Request Created!**
          - Author: @sofiamelnyk6770
          - PR Title: ${{ github.event.pull_request.title }}
          - PR URL: ${{ github.event.pull_request.html_url }}
          - Action: ${{ github.event.action }}
